apiVersion: hoho.dev/v1
kind: HoneypotPack
metadata:
  id: cve-2021-41773_apache-2-4-49-2-4-50-traversal-rce
  name: Apache httpd 2.4.49/2.4.50 Traversal + RCE (low)
  interaction: low
  tags:
    - cve
    - cve:2021-41773
    - cve:2021-42013
    - product:apache-httpd
    - technique:path-traversal
    - technique:rce
  description: >
    Low-interaction emulation for Apache httpd 2.4.49/2.4.50 path traversal and
    CGI RCE probe traffic. Captures exploit attempts and returns plausible
    Apache-style responses without running vulnerable software.
storage:
  backend: filesystem
  root: ./run/artifacts
limits:
  max_body_bytes: 1048576
  max_upload_bytes: 10485760
  max_artifacts_per_request: 5
telemetry:
  emit_events: true
  redact_headers:
    - Authorization
    - Cookie
listen:
  - host: 0.0.0.0
    port: 8088
behaviors:
  - name: traversal-passwd-probe
    match:
      method: GET
      pathRegex: "^/(cgi-bin|icons)/.*(%2e|\\.){1,2}(%2f|/).*(etc/passwd)"
    actions:
      - emit_event:
          verdict: exploit
          tags:
            - cve:2021-41773
            - cve:2021-42013
            - product:apache-httpd
            - technique:path-traversal
          indicators:
            - file-read-probe
      - delay:
          ms: 120
          jitterMs: 80
    respond:
      status: 200
      headers:
        Content-Type: text/plain
        Server: Apache/2.4.49 (Unix)
      body: "root:x:0:0:root:/root:/bin/bash\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\n"

  - name: cgi-rce-binsh-probe
    match:
      method: POST
      pathRegex: "^/cgi-bin/.*(%2e|\\.){1,2}(%2f|/).*(bin/sh)$"
    actions:
      - emit_event:
          verdict: exploit
          tags:
            - cve:2021-41773
            - cve:2021-42013
            - product:apache-httpd
            - technique:rce
          indicators:
            - cgi-bin-sh-exec
      - store_body:
          kind: request_body
          gzip: true
      - delay:
          ms: 180
          jitterMs: 120
    respond:
      status: 200
      headers:
        Content-Type: text/plain
        Server: Apache/2.4.50 (Unix)
      body: "Status: 200\nContent-Type: text/plain\n\n"

  - name: traversal-normalization-probe
    match:
      method: GET
      pathRegex: "^/cgi-bin/.*(%25){1,2}32%65(%25){1,2}32%65.*(etc/passwd|bin/sh)"
    actions:
      - emit_event:
          verdict: exploit
          tags:
            - cve:2021-42013
            - product:apache-httpd
            - technique:path-traversal
          indicators:
            - double-encoded-dot-segments
      - delay:
          ms: 140
          jitterMs: 90
    respond:
      status: 403
      headers:
        Content-Type: text/html
        Server: Apache/2.4.50 (Unix)
      body: "<html><body><h1>403 Forbidden</h1></body></html>"

  - name: server-root
    match:
      method: GET
      path: /
    actions:
      - emit_event:
          verdict: probe
          tags:
            - product:apache-httpd
            - landing
          indicators: []
    respond:
      status: 200
      headers:
        Content-Type: text/html
        Server: Apache/2.4.49 (Unix)
      body: "<html><body><h1>It works!</h1></body></html>"

  - name: default
    match:
      pathGlob: "/*"
    actions:
      - emit_event:
          verdict: unknown
          tags:
            - product:apache-httpd
          indicators: []
    respond:
      status: 404
      headers:
        Content-Type: text/plain
        Server: Apache/2.4.49 (Unix)
      body: "Not Found"
