apiVersion: hoho.dev/v1
kind: HoneypotPack
metadata:
  id: cve-2025-55182_nextjs_react2shell_rce
  name: cve-2025-55182_nextjs_react2shell_rce
  interaction: high
  tags:
    - web
    - react
    - nextjs
    - react-server-components
    - cve-2025-55182
    - rce
  description: React/Next.js (RSC) React2Shell high-interaction lure with inbound, filesystem, egress, and packet telemetry.
storage:
  backend: filesystem
  root: ./run/artifacts
telemetry:
  emit_events: true
  redact_headers:
    - Authorization
    - Cookie
stack:
  runtime: compose
  services:
    nextjs:
      image: node:20-alpine
      working_dir: /opt/react2shell
      command:
        - node
        - /opt/react2shell/server.js
      ports:
        - 8105:3000
      environment:
        NODE_ENV: production
        NEXT_TELEMETRY_DISABLED: "1"
      volumes:
        - ./app:/opt/react2shell:ro
        - nextcache:/var/lib/nextcache
        - tmpdata:/tmp
      networks:
        - frontend
        - hp_internal
        - hp_external
sensors:
  - name: proxy-sensor
    type: proxy
    config:
      upstream: http://nextjs:3000
      listen_port: 8080
      #keep_host_header: true
    attach:
      service: nextjs
  - name: fsmon-sensor
    type: fsmon
    config:
      watch:
        - /tmp
        - /var/lib/nextcache
      allow_globs:
        - "**"
      deny_globs:
        - "**/*.log"
      max_bytes: 524288
    attach:
      service: nextjs
  - name: pcap-sensor
    type: pcap
    config:
      interface: any
      rotate_seconds: 60
      rotate_count: 20
    attach:
      service: nextjs
  - name: egress
    type: egress_proxy
    attach:
      services: ["nextjs"]
    config:
      listen_host: "0.0.0.0"
      listen_port: 3128
      force_egress_via_proxy: false
      tls_mitm:
        enabled: true
        install_trust:
          also_set_env_bundles: true
          extra_commands: []
      capture:
        enabled: true
        bodies: "*"
        max_bytes: 52428800
        store_ok_only: true
        min_bytes: 1
        redact_headers: ["Authorization", "Cookie"]
