apiVersion: hoho.dev/v1
kind: HoneypotPack
metadata:
  id: cve-2020-25213_wp_file_upload
  name: cve-2020-25213
  interaction: high
  tags:
    - web
    - stack
    - wordpress
  description: WordPress + MariaDB high-interaction stack with fsmon, proxy, and pcap sidecars.
storage:
  backend: filesystem
  root: ./run/artifacts
telemetry:
  emit_events: true
  redact_headers:
    - Authorization
    - Cookie
  forwarding:
    enabled: true
    hub_url: "${HOHO_HUB_URL}"
    token_env: "HOHO_HUB_TOKEN"
stack:
  runtime: compose
  services:
    db:
      image: mariadb:11
      environment:
        MARIADB_DATABASE: wordpress
        MARIADB_USER: wordpress
        MARIADB_PASSWORD: wordpress
        MARIADB_ROOT_PASSWORD: rootpass
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        - frontend
    web:
      image: funway/cve-2020-25213
      depends_on:
        - db
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
      ports:
        - 8088:80
      volumes:
        - webdata:/var/www/html
      networks:
        - frontend
sensors:
  - name: proxy-sensor
    type: proxy
    config:
      upstream: http://web:80
      listen_port: 8080
    attach:
      service: web
  - name: fsmon-sensor
    type: fsmon
    config:
      watch:
        - /var/www/html
        - /var/www/html/wp-content/uploads
      allow_globs:
        - "**"
      deny_globs:
        - "**/cache/**"
      max_bytes: 262144
    attach:
      service: web
  - name: pcap-sensor
    type: pcap
    config:
      interface: any
      rotate_seconds: 60
      rotate_count: 10
    attach:
      service: web
  - name: egress
    type: egress_proxy
    attach:
      services: ["web"]    # list of stack service names to proxy egress for
    config:
      listen_host: "0.0.0.0"
      listen_port: 3128

      force_egress_via_proxy: false

      tls_mitm:
        enabled: true
        install_trust:
          also_set_env_bundles: true  # SSL_CERT_FILE/REQUESTS_CA_BUNDLE/CURL_CA_BUNDLE/NODE_EXTRA_CA_CERTS
          extra_commands: []          # optional extra per-image commands

      capture:
        enabled: true
        bodies: "*"                # DEFAULT: capture all response bodies
        max_bytes: 52428800        # 50MB cap per response
        store_ok_only: true        # default true (2xx/3xx)
        min_bytes: 1               # default 1 (set higher if you want to reduce noise)
        redact_headers: ["Authorization","Cookie"]
  - name: falco-sensor
    type: falco
    attach:
      services: ["web"]          # stack service(s) to scope on (optional but recommended)
    config:
      # Falco runtime mode (renderer supports "privileged"; runs with host net + mounts)
      mode: privileged

      # Falco engine (default is modern_ebpf)
      engine: modern_ebpf

      # Minimum Falco priority to emit
      priority_min: Warning

      # If true, default rules become more "any exec" noisy (good for RCE labs)
      any_exec: true

      # Extra fields appended into emitted events (comma-joined list)
      append_fields:
        - honeypot_id=cve-2021-41773_42013_apache_rce
        - sensor=falco

      # Optional: add your own rules files.
      # Defaults are always loaded from /app/rules/hoho_rules.yaml in the Falco image,
      # then custom files from this honeypot are appended after defaults.
      rules:
        - ./falco/custom_rules.yaml

      # Optional enforcement (OFF by default)
      enforce:
        enabled: false
        match_priorities: ["Critical", "Error"]
        match_rules: []
        action: stop_container       # stop_container | stop_service | stop_stack
        cooldown_seconds: 60