apiVersion: hoho.dev/v1
kind: HoneypotPack
metadata:
  id: cve-2021-41773_42013
  name: cve-2021-41773_42013
  interaction: high
  tags:
    - web
    - apache
    - cve-2021-41773
    - cve-2021-42013
  description: Apache httpd 2.4.49/2.4.50 high-interaction stack with traversal/RCE-oriented telemetry capture.
storage:
  backend: filesystem
  root: ./run/artifacts
telemetry:
  emit_events: true
  redact_headers:
    - Authorization
    - Cookie
stack:
  runtime: compose
  services:
    apache:
      image: blueteamsteve/cve-2021-41773:with-cgid
      ports:
        - 8096:80
      volumes:
        - ./packs/high/cve-2021-41773_42013/htdocs:/usr/local/apache2/htdocs
        - ./packs/high/cve-2021-41773_42013/cgi-bin:/usr/local/apache2/cgi-bin
        - tmpdata:/tmp
      networks:
        - frontend
        - hp_internal
sensors:
  - name: proxy-sensor
    type: proxy
    config:
      upstream: http://apache:80
      listen_port: 8080
    attach:
      service: apache
  - name: fsmon-sensor
    type: fsmon
    config:
      watch:
        - /usr/local/apache2/htdocs
        - /usr/local/apache2/cgi-bin
        - /tmp
      allow_globs:
        - "**"
      deny_globs:
        - "**/*.log"
      max_bytes: 524288
    attach:
      service: apache
  - name: pcap-sensor
    type: pcap
    config:
      interface: any
      rotate_seconds: 60
      rotate_count: 20
    attach:
      service: proxy-sensor
  - name: egress
    type: egress_proxy
    attach:
      services: ["apache"]    # list of stack service names to proxy egress for
    config:
      listen_host: "0.0.0.0"
      listen_port: 3128

      force_egress_via_proxy: true

      tls_mitm:
        enabled: true
        install_trust:
          also_set_env_bundles: true  # SSL_CERT_FILE/REQUESTS_CA_BUNDLE/CURL_CA_BUNDLE/NODE_EXTRA_CA_CERTS
          extra_commands: []          # optional extra per-image commands

      capture:
        enabled: true
        bodies: "*"                # DEFAULT: capture all response bodies
        max_bytes: 52428800        # 50MB cap per response
        store_ok_only: true        # default true (2xx/3xx)
        min_bytes: 1               # default 1 (set higher if you want to reduce noise)
        redact_headers: ["Authorization","Cookie"]
