apiVersion: hoho.dev/v1
kind: HoneypotPack
metadata:
  id: cve-2017-12629_solr_rce
  name: cve-2017-12629_solr_rce
  interaction: high
  tags:
    - web
    - apache-solr
    - cve-2017-12629
    - rce
  description: Apache Solr 7.1.0 high-interaction stack with DIH-oriented telemetry capture for CVE-2017-12629.
storage:
  backend: filesystem
  root: ./run/artifacts
telemetry:
  emit_events: true
  redact_headers:
    - Authorization
    - Cookie
stack:
  runtime: compose
  services:
    solr:
      image: solr:7.1
      command:
        - solr-precreate
        - gettingstarted
      ports:
        - 8097:8983
      volumes:
        - solrdata:/var/solr
      networks:
        - frontend
sensors:
  - name: proxy-sensor
    type: proxy
    config:
      upstream: http://solr:8983
      listen_port: 8080
      keep_host_header: true
    attach:
      service: solr
  - name: fsmon-sensor
    type: fsmon
    config:
      watch:
        - /var/solr
      allow_globs:
        - "**"
      deny_globs:
        - "**/*.log"
      max_bytes: 524288
    attach:
      service: solr
  - name: pcap-sensor
    type: pcap
    config:
      interface: any
      rotate_seconds: 60
      rotate_count: 20
    attach:
      service: proxy-sensor
  - name: egress
    type: egress_proxy
    attach:
      services: ["solr"]
    config:
      listen_host: "0.0.0.0"
      listen_port: 3128
      force_egress_via_proxy: false
      tls_mitm:
        enabled: true
        install_trust:
          also_set_env_bundles: true
          extra_commands: []
      capture:
        enabled: true
        bodies: "*"
        max_bytes: 52428800
        store_ok_only: true
        min_bytes: 1
        redact_headers: ["Authorization", "Cookie"]
